# Generated by Django 4.0 on 2024-11-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('modern', 'モダン'), ('classic', 'クラシック'), ('scandinavian', '北欧')], max_length=20)),
                ('size', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
