# Generated by Django 4.0 on 2024-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_furniture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='furniture',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
