# Generated by Django 4.0 on 2025-01-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainapp', '0003_furniture_height_furniture_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='size',
        ),
        migrations.AddField(
            model_name='furniture',
            name='depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='furniture_images/'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='style',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='room_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
