# Generated by Django 4.0 on 2025-01-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_furniture_size_furniture_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture_images/'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='style',
            field=models.CharField(choices=[('modern', 'ソファ'), ('classic', '机'), ('industrial', '椅子'), ('scandinavian', 'ランプ'), ('bohemian', 'その他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='width',
            field=models.IntegerField(),
        ),
    ]
